language: c

compiler:
  - clang
  - gcc

before_script:
  - ./autogen.sh

script:
  - ./configure --enable-code-coverage && make && make check

after_success:
  - mv src/sas/.libs/*.gc* .
  - mv src/spss/.libs/*.gc* .
  - mv src/stata/.libs/*.gc* .
  - mv src/.libs/*.gc* .
  - bash <(curl -s https://codecov.io/bash)
