language: c
sudo: required

compiler:
  - clang
  - gcc
  - gcc-7

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - gcc-7
    - binutils

before_script:
  - ./autogen.sh

script:
  - ./configure --enable-code-coverage --enable-sanitizers && make && make check
  - cat test-suite.log

after_success:
  - mv src/sas/.libs/*.gc* .
  - mv src/spss/.libs/*.gc* .
  - mv src/stata/.libs/*.gc* .
  - mv src/.libs/*.gc* .
  - bash <(curl -s https://codecov.io/bash)
