language: c
sudo: required

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:jonathonf/gcc-7.2
  - sudo apt-get update -q
  - sudo apt-get install gcc-7.2 -y

before_script:
  - ./autogen.sh

script:
  - ./configure --enable-code-coverage && make && make check

after_success:
  - mv src/sas/.libs/*.gc* .
  - mv src/spss/.libs/*.gc* .
  - mv src/stata/.libs/*.gc* .
  - mv src/.libs/*.gc* .
  - bash <(curl -s https://codecov.io/bash)
